# Types
type Client {
  id: ID!
  name: String!
  age: Int!
  documents: [Document]
  relatives: [Relative]
}

type Document {
  id: ID!
  type: String!
  number: String!
  issueDate: String!
  expiryDate: String
}

type Relative {
  id: ID!
  relationType: String!
  name: String!
  age: Int!
}

# Queries
type Query {
  # Получить информацию о клиенте по ID
  client(id: ID!): Client

  # Получить список документов клиента по ID
  clientDocuments(id: ID!): [Document]

  # Получить нформацию о родственниках клиента по ID
  clientRelatives(id: ID!): [Relative]
}